// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcmjqsvqkmexvwwhwjfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbWpxc3Zxa21leHZ3d2h3amZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDMzMDYsImV4cCI6MjA2NzQ3OTMwNn0.XmofSI1QdHI9R1AH52sHAHLkHBCGCALKX2R3hlBGbos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
